name: twinkle

services:
  shiny:
    image: ghcr.io/mrc-ide/twinkle2:cli
    environment:
      TWINKLE_ROOT: "/shiny"
      TWINKLE_CONFIG: "/site.yml"
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - shiny-data:/shiny
      - ./site.yml:/site.yml:ro
      - ./shiny-server.conf:/etc/shiny-server/shiny-server.conf:ro

  haproxy:
    image: haproxy:latest
    depends_on:
      shiny:
        condition: service_started
        restart: true
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  apache:
    image: httpd:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      haproxy:
        condition: service_started
        restart: true
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:ro

volumes:
  shiny-data:
    # This container is marked as 'external' so that we can poke at it
    # directly, but that might not really be needed.  Otherwise it
    # will be managed by docker compose (being created where needed
    # etc), which might be fine too.
    external: true
    name: shiny-data
